#cloud-config
# modules/vps-definition/cloud-init.yaml

users:
  - name: ubuntu
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
%{ for key in ssh_public_keys ~}
      - ${key.publickey}
%{ endfor ~}

# Update system and install basic packages
packages:
  - curl
  - wget
  - git
  - htop
  - nginx
  - ufw

# Configure firewall and services
runcmd:
  # Update system
  - apt update && apt upgrade -y
  
  # Configure UFW firewall
  - ufw --force enable
  - ufw allow ssh
  - ufw allow http
  - ufw allow https
  
  # Enable and start nginx (but don't create default content)
  - systemctl enable nginx
  - systemctl start nginx
  
  # Remove default nginx content (you'll add your own)
  - rm -f /var/www/html/index.nginx-debian.html

final_message: "Ubuntu 24.04 VPS setup complete! SSH access ready."